name: Wordpress PHP 7.4 / 8.0 images CI

on:
  workflow_dispatch:

jobs:
  Buster74:
    name: "PHP 7.4 buster"
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # https://github.com/docker/buildx/issues/495#issuecomment-761562905
      - name: Adding custom builder
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker buildx create --name multiarch --driver docker-container --use
          docker buildx inspect --bootstrap
      # https://github.com/docker/login-action
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      # https://github.com/actions/starter-workflows/issues/68
      # https://github.com/firepress-org/rclone-in-docker/blob/master/.github/workflows/ci_dockerfile_is_master.yml
      - name: Set env from file
        run: grep -e ^PHP74.*= .env.build >> $GITHUB_ENV
      - name: Build php:7.4-zts-buster
        if: ${{ env.PHP74 != '' }}
        run: |
          docker buildx build \
            --file Dockerfile.buster \
            --platform linux/amd64,linux/386,linux/arm64,linux/arm/v7 \
            --tag carlesbarreda/wordpress:5.6.2-php7.4-zts-buster \
            --tag carlesbarreda/wordpress:php7.4-zts-buster \
            --build-arg VERSION=$PHP74 \
            --build-arg VARIANT=zts \
            --progress=plain \
            --no-cache \
            --push .
      - name: Build php:7.4-fpm-buster
        if: ${{ env.PHP74 != '' }}
        run: |
          docker buildx build \
            --file Dockerfile.buster \
            --platform linux/amd64,linux/386,linux/arm64,linux/arm/v7 \
            --tag carlesbarreda/wordpress:5.6.2-php7.4-fpm-buster \
            --tag carlesbarreda/wordpress:php7.4-fpm-buster \
            --build-arg VERSION=$PHP74 \
            --build-arg VARIANT=fpm \
            --progress=plain \
            --no-cache \
            --push .

  Alpine74:
    name: "PHP 7.4 alpine"
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # https://github.com/docker/buildx/issues/495#issuecomment-761562905
      - name: Adding custom builder
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker buildx create --name multiarch --driver docker-container --use
          docker buildx inspect --bootstrap
      # https://github.com/docker/login-action
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      # https://github.com/actions/starter-workflows/issues/68
      - name: Set env from file
        run: grep -e ^PHP74.*= .env.build >> $GITHUB_ENV
      - name: Build php:7.4-zts-alpine
        if: ${{ env.PHP74 != '' }}
        run: |
          docker buildx build \
            --file Dockerfile.alpine \
            --platform linux/amd64,linux/386,linux/arm64,linux/arm/v7 \
            --tag carlesbarreda/wordpress:5.6.2-php7.4-zts-alpine \
            --tag carlesbarreda/wordpress:5.6.2-php7.4-zts \
            --tag carlesbarreda/wordpress:php7.4-zts-alpine \
            --tag carlesbarreda/wordpress:php7.4-zts \
            --build-arg VERSION=$PHP74 \
            --build-arg VARIANT=zts \
            --progress=plain \
            --no-cache \
            --push .
      - name: Build php:7.4-fpm-alpine
        if: ${{ env.PHP74 != '' }}
        run: |
          docker buildx build \
            --file Dockerfile.alpine \
            --platform linux/amd64,linux/386,linux/arm64,linux/arm/v7 \
            --tag carlesbarreda/wordpress:5.6.2-php7.4-fpm-alpine \
            --tag carlesbarreda/wordpress:5.6.2-php7.4-fpm \
            --tag carlesbarreda/wordpress:php7.4-fpm-alpine \
            --tag carlesbarreda/wordpress:php7.4-fpm \
            --build-arg VERSION=$PHP74 \
            --build-arg VARIANT=fpm \
            --progress=plain \
            --no-cache \
            --push .

  Buster80:
    name: "PHP 8.0 buster"
    needs: [Buster74, Alpine74]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # https://github.com/docker/buildx/issues/495#issuecomment-761562905
      - name: Adding custom builder
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker buildx create --name multiarch --driver docker-container --use
        #  docker buildx inspect --bootstrap
      # https://github.com/docker/login-action
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      # https://github.com/actions/starter-workflows/issues/68
      - name: Set env from file
        run: grep -e ^PHP80.*= .env.build >> $GITHUB_ENV
      - name: Build php:8.0-zts-buster
        if: ${{ env.PHP80 != '' }}
        run: |
          docker buildx build \
            --file Dockerfile.buster \
            --platform linux/amd64,linux/386,linux/arm64,linux/arm/v7 \
            --tag carlesbarreda/wordpress:5.6.2-php8.0-zts-buster \
            --tag carlesbarreda/wordpress:php8.0-zts-buster \
            --build-arg VERSION=$PHP80 \
            --build-arg VARIANT=zts \
            --progress=plain \
            --no-cache \
            --push .
      - name: Build php:8.0-fpm-buster
        if: ${{ env.PHP80 != '' }}
        run: |
          docker buildx build \
            --file Dockerfile.buster \
            --platform linux/amd64,linux/386,linux/arm64,linux/arm/v7 \
            --tag carlesbarreda/wordpress:5.6.2-php8.0-fpm-buster \
            --tag carlesbarreda/wordpress:php8.0-fpm-buster \
            --build-arg VERSION=$PHP80 \
            --build-arg VARIANT=fpm \
            --progress=plain \
            --no-cache \
            --push .

  # This is the last job
  Alpine80:
    name: "PHP 8.0 alpine"
    needs: [Buster74, Alpine74]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # https://github.com/docker/buildx/issues/495#issuecomment-761562905
      - name: Adding custom builder
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker buildx create --name multiarch --driver docker-container --use
        #  docker buildx inspect --bootstrap
      # https://github.com/docker/login-action
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      # https://github.com/actions/starter-workflows/issues/68
      - name: Set env from file
        run: grep -e ^PHP80.*= .env.build >> $GITHUB_ENV
      - name: Build php:8.0-fpm-alpine
        if: ${{ env.PHP80 != '' }}
        run: |
          docker buildx build \
            --file Dockerfile.alpine \
            --platform linux/amd64,linux/386,linux/arm64,linux/arm/v7 \
            --tag carlesbarreda/wordpress:5.6.2-php8.0-fpm-alpine \
            --tag carlesbarreda/wordpress:5.6.2-php8.0-fpm \
            --tag carlesbarreda/wordpress:php8.0-fpm-alpine \
            --tag carlesbarreda/wordpress:php8.0-fpm \
            --tag carlesbarreda/wordpress:latest \
            --build-arg VERSION=$PHP80 \
            --build-arg VARIANT=fpm \
            --progress=plain \
            --no-cache \
            --push .
