name: Manual Docker Image CI

#on:
#  push:
#    branches: main

#on:
#  workflow_dispatch:
#    inputs:
#      tags:
#        description: 'Cerbot version tag'
#        required: true
#        default: 'v1.10.1'
#      latest:
#        description: 'Is latest?'
#        required: true
#        default: 'yes'

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: build the image
        run: |
          docker buildx build \
            --file Dockerfile.wordpress-php7.4-fpm-alpine.buildx \
            --platform linux/amd64,linux/386,linux/arm64,linux/arm/v7 \
            --tag carlesbarreda/wordpress:5.6.2-php7.4-fpm-alpine \
            --tag carlesbarreda/wordpress:php7.4-fpm-alpine \
            --tag carlesbarreda/wordpress:5.6.2-php7.4-fpm \
            --tag carlesbarreda/wordpress:php7.4-fpm \
            --push .
          docker buildx build \
            --file Dockerfile.wordpress-php8.0-fpm-alpine.buildx \
            --platform linux/amd64,linux/386,linux/arm64,linux/arm/v7 \
            --tag carlesbarreda/wordpress:5.6.2-php8.0-fpm-alpine \
            --tag carlesbarreda/wordpress:php8.0-fpm-alpine \
            --tag carlesbarreda/wordpress:5.6.2-php8.0-fpm \
            --tag carlesbarreda/wordpress:php8.0-fpm \
            --tag carlesbarreda/wordpress:latest \
            --push .
